=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/monitoringrules/actions_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿marco (polimi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ac="http://www.modaclouds.eu/xsd/2.0/actions_schema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" targetNamespace="http://www.modaclouds.eu/xsd/2.0/actions_schema" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:version="2.1">
	<xs:element name="availableActions">
		<xs:annotation>
			<xs:documentation>The list of available actions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="availableAction" type="ac:availableAction" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property name="availableActions"/>
						</xs:appinfo>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="availableAction">
		<xs:sequence>
			<xs:element name="requiredParameter" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="requiredParameters"/>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/examples/monitoring_actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<availableActions xmlns="http://www.modaclouds.eu/xsd/2.0/actions_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/2.0/actions_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/monitoringrules/actions_schema.xsd">
	<availableAction name="OutputMetric">
		<requiredParameter>name</requiredParameter>
	</availableAction>
	<availableAction name="EnableMonitoringRule" />
	<availableAction name="DisableMonitoringRule" />
	<availableAction name="SetSamplingProbability">
		<requiredParameter>probability</requiredParameter>
	</availableAction>
	<availableAction name="SetSamplingTime">
		<requiredParameter>time</requiredParameter>
	</availableAction>
</availableActions>
