=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/monitoringrules/grouping_categories_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿marco (polimi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:gc="http://www.modaclouds.eu/xsd/2.0/grouping_categories_schema"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	targetNamespace="http://www.modaclouds.eu/xsd/2.0/grouping_categories_schema"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	jaxb:version="2.1">
	<xs:element name="groupingCategories">
		<xs:annotation>
			<xs:documentation>A list of grouping categories</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="groupingCategory" type="gc:groupingCategory"
					minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property name="groupingCategories" />
						</xs:appinfo>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="groupingCategory">
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
</xs:schema>

=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/examples/monitoring_grouping_categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<groupingCategories
	xmlns="http://www.modaclouds.eu/xsd/2.0/grouping_categories_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/2.0/grouping_categories_schema
	https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/monitoringrules/grouping_categories_schema.xsd">
	<groupingCategory name="CloudProvider" />
	<groupingCategory name="Region" />
	<groupingCategory name="Location" />
	<groupingCategory name="Zone" />
	<groupingCategory name="Method" />
	<groupingCategory name="Component" />
	<groupingCategory name="ExternalComponent" />
	<groupingCategory name="InternalComponent" />
	<groupingCategory name="PaaSService" />
	<groupingCategory name="VM" />
</groupingCategories>
