=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/commons/aggregate_functions_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿marco (polimi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:af="http://www.modaclouds.eu/xsd/2.0/aggregate_functions_schema"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	targetNamespace="http://www.modaclouds.eu/xsd/2.0/aggregate_functions_schema"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	jaxb:version="2.1">
	<xs:element name="aggregateFunctions">
		<xs:annotation>
			<xs:documentation>A list of aggregating functions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="aggregateFunction" type="af:aggregateFunction"
					minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property name="aggregateFunctions" />
						</xs:appinfo>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="aggregateFunction">
		<xs:sequence>
			<xs:element name="requiredParameter" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="requiredParameters" />
					</xs:appinfo>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="defaultValue" type="xs:string"
								use="optional" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="computedBy" type="af:aggregator" />
	</xs:complexType>
	<xs:simpleType name="aggregator">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DeterministicDataAnalyzer" />
			<xs:enumeration value="JAVAStatisticalDataAnalyzer" />
			<xs:enumeration value="MATLABStatisticalDataAnalyzer" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/examples/monitoring_aggregate_functions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<aggregateFunctions
	xmlns="http://www.modaclouds.eu/xsd/2.0/aggregate_functions_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/2.0/aggregate_functions_schema 
	https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/commons/aggregate_functions_schema.xsd">
	<aggregateFunction name="Average" computedBy="DeterministicDataAnalyzer">
	</aggregateFunction>
	<aggregateFunction name="Percentile" computedBy="DeterministicDataAnalyzer">
		<requiredParameter>thPercentile</requiredParameter>
	</aggregateFunction>
	<aggregateFunction name="Max" computedBy="DeterministicDataAnalyzer">
	</aggregateFunction>
	<aggregateFunction name="Min" computedBy="DeterministicDataAnalyzer">
	</aggregateFunction>
	<aggregateFunction name="ForecastingML" computedBy="JAVAStatisticalDataAnalyzer">
		<requiredParameter>otherTarget1</requiredParameter>
		<requiredParameter>otherMetric1</requiredParameter>
		<requiredParameter>method</requiredParameter>
		<requiredParameter>predictionStep</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
	<aggregateFunction name="ForecastingTimeSeriesAR"
		computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>order</requiredParameter>
		<requiredParameter>forecastPeriod</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
	<aggregateFunction name="ForecastingTimeSeriesARMA"
		computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>autoregressive</requiredParameter>
		<requiredParameter>movingAverage</requiredParameter>
		<requiredParameter>forecastPeriod</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
		<aggregateFunction name="ForecastingTimeSeriesARIMA"
		computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>autoregressive</requiredParameter>
		<requiredParameter>integrated</requiredParameter>
		<requiredParameter>movingAverage</requiredParameter>
		<requiredParameter>forecastPeriod</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
	<aggregateFunction name="EstimationCI" computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>window</requiredParameter>
		<requiredParameter>nCPU</requiredParameter>
		<requiredParameter>CPUUtilTarget</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
	<aggregateFunction name="EstimationFCFS" computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>window</requiredParameter>
		<requiredParameter>nCPU</requiredParameter>
		<requiredParameter>CPUUtilTarget</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
		<aggregateFunction name="EstimationUBO" computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>window</requiredParameter>
		<requiredParameter>CPUUtilTarget</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
		<aggregateFunction name="EstimationUBR" computedBy="MATLABStatisticalDataAnalyzer">
		<requiredParameter>window</requiredParameter>
		<requiredParameter>nCPU</requiredParameter>
		<requiredParameter>CPUUtilTarget</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
	<aggregateFunction name="Correlation" computedBy="JAVAStatisticalDataAnalyzer">
		<requiredParameter>otherTarget1</requiredParameter>
		<requiredParameter>otherMetric1</requiredParameter>
		<requiredParameter>method</requiredParameter>
		<requiredParameter>isTraining</requiredParameter>
		<requiredParameter>returnedMetric</requiredParameter>
	</aggregateFunction>
</aggregateFunctions>
