=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/commons/metrics_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿marco (polimi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mt="http://www.modaclouds.eu/xsd/1.0/metrics_schema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" targetNamespace="http://www.modaclouds.eu/xsd/1.0/metrics_schema" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:version="2.1">
	<xs:element name="metrics">
		<xs:annotation>
			<xs:documentation>A list of metrics</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metric" type="mt:metric" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property name="metrics"/>
						</xs:appinfo>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="metric">
		<xs:sequence>
			<xs:element name="requiredParameter" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="requiredParameters"/>
					</xs:appinfo>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="defaultValue" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/examples/qos_metrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<metrics xmlns="http://www.modaclouds.eu/xsd/1.0/metrics_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/metrics_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/commons/metrics_schema.xsd">
	<metric name="CPUUtilization" />
	<metric name="ResponseTime" />
	<metric name="Replication" />
	<metric name="Ram" />
	<metric name="Availability" />
	<metric name="Cores" />
	<metric name="ResourceType" />
	<metric name="ServiceName" />
	<metric name="Provider" />
	<metric name="WorkloadDistribution" />
</metrics>
