=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/s4cextension/resource_model_extension.xsd
<?xml version="1.0"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿Gibbo (GB) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:resex="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension" targetNamespace="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension" elementFormDefault="qualified">
	<!--The root-->
	<xs:element name="resourceModelExtension">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="resourceContainer" type="resex:resourceContainer" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="iaasService">
		<xs:sequence>
			<xs:element name="resourceSizeID" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<!--The name of specific IaaS resource (e.g. On-Demand Extra Large Instance) should we list them all with an enumeration?-->
			<xs:element name="location" type="resex:location" minOccurs="0" maxOccurs="1"/>
			<xs:element name="replicas" type="resex:replica" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="serviceType" type="xs:string" use="required"/>
		<xs:attribute name="serviceName" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="paasService">
		<xs:attribute name="serviceType" type="xs:string" use="required"/>
		<xs:attribute name="serviceName" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="location">
		<xs:attribute name="region" type="xs:string" use="optional"/>
		<xs:attribute name="zone" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="replica">
		<xs:sequence>
			<xs:element name="replicaElement" type="resex:replicaElement" minOccurs="24" maxOccurs="24"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="resourceContainer">
		<xs:sequence>
			<xs:choice>
				<!--Either a PaaS or a IaaS-->
				<xs:element name="cloudPlatform" type="resex:paasService"/>
				<xs:element name="cloudResource" type="resex:iaasService"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="provider" type="xs:string" use="optional"/>
		<!--Must be the same  ID of the resourceContainer in Palladio-->
	</xs:complexType>
	<xs:complexType name="replicaElement">
		<xs:attribute name="hour" type="xs:int" use="required"/>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/SimpleModel/ResourceContainerExtension.xml
<?xml version="1.0"?>
<resourceModelExtension xmlns="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension ../s4cextension/resource_model_extension.xsd">
  <resourceContainer id="39b66f7c-f48e-4ed1-bce1-511a1cf8606d__resourceContainer" name="CloudNodeInstance_SampleCloudNode" provider="Amazon">
    <cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
      <resourceSizeID>On-Demand Micro Instance</resourceSizeID>
      <replicas>
        <replicaElement hour="0" value="1"/>
        <replicaElement hour="1" value="1"/>
        <replicaElement hour="2" value="1"/>
        <replicaElement hour="3" value="1"/>
        <replicaElement hour="4" value="1"/>
        <replicaElement hour="5" value="1"/>
        <replicaElement hour="6" value="1"/>
        <replicaElement hour="7" value="1"/>
        <replicaElement hour="8" value="1"/>
        <replicaElement hour="9" value="1"/>
        <replicaElement hour="10" value="1"/>
        <replicaElement hour="11" value="1"/>
        <replicaElement hour="12" value="1"/>
        <replicaElement hour="13" value="1"/>
        <replicaElement hour="14" value="1"/>
        <replicaElement hour="15" value="1"/>
        <replicaElement hour="16" value="1"/>
        <replicaElement hour="17" value="1"/>
        <replicaElement hour="18" value="1"/>
        <replicaElement hour="19" value="1"/>
        <replicaElement hour="20" value="1"/>
        <replicaElement hour="21" value="1"/>
        <replicaElement hour="22" value="1"/>
        <replicaElement hour="23" value="1"/>
      </replicas>
    </cloudResource>
  </resourceContainer>
</resourceModelExtension>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/mic/ContainerExtension.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<resourceModelExtension xmlns="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension C:/Users/GiovanniPaolo/git/modaclouds-qos-models/metamodels/s4cextension/resource_model_extension.xsd">
		<resourceContainer provider="Amazon" id="_J_O-sIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_LP3gIIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
			<location region="us-east"/>
			</cloudResource>
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_MNm6wIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_LnOQMIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_LZ_FcIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_LhbKMIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_Lt6uEIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>
		<resourceContainer provider="Amazon" id="_H9DrkIGSEeKo6LTSAnjWxg">
			<cloudResource serviceName="Elastic Compute Cloud (EC2)" serviceType="Compute">
				<location region="us-east"/>
			</cloudResource> 
		</resourceContainer>	
</resourceModelExtension>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/mic2/ResourceContainerExtension.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resourceModelExtension xmlns="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/2013/6/resource-model-extension https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/s4cextension/resource_model_extension.xsd">
    <resourceContainer id="_JWHSgMdLEeSzTs-iRu8Llw" name="FrontEnd" provider="Amazon">
        <cloudElement serviceCategory="IaaS" serviceType="Compute" serviceName="Elastic Compute Cloud (EC2)">
            <resourceSizeID>i2.4xlarge</resourceSizeID>
            <location region="us-west-2"/>
            <replicas>
                <replicaElement hour="0" value="1"/>
                <replicaElement hour="1" value="1"/>
                <replicaElement hour="2" value="1"/>
                <replicaElement hour="3" value="1"/>
                <replicaElement hour="4" value="1"/>
                <replicaElement hour="5" value="1"/>
                <replicaElement hour="6" value="1"/>
                <replicaElement hour="7" value="1"/>
                <replicaElement hour="8" value="1"/>
                <replicaElement hour="9" value="3"/>
                <replicaElement hour="10" value="8"/>
                <replicaElement hour="11" value="12"/>
                <replicaElement hour="12" value="5"/>
                <replicaElement hour="13" value="6"/>
                <replicaElement hour="14" value="8"/>
                <replicaElement hour="15" value="12"/>
                <replicaElement hour="16" value="12"/>
                <replicaElement hour="17" value="8"/>
                <replicaElement hour="18" value="3"/>
                <replicaElement hour="19" value="1"/>
                <replicaElement hour="20" value="1"/>
                <replicaElement hour="21" value="1"/>
                <replicaElement hour="22" value="1"/>
                <replicaElement hour="23" value="1"/>
            </replicas>
        </cloudElement>
    </resourceContainer>
</resourceModelExtension>
