=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/qosconstraints/qos_constraints_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿marco (polimi) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cons="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
	targetNamespace="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
	xmlns:pa="http://www.modaclouds.eu/xsd/1.0/parameter_schema" 
	elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	jaxb:version="2.1">
	<xs:import namespace="http://www.modaclouds.eu/xsd/1.0/parameter_schema"
		schemaLocation="../commons/parameter_schema.xsd" />
	<xs:element name="constraints">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="constraint" type="cons:constraint"
					minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property name="constraints" />
						</xs:appinfo>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="set">
		<xs:sequence>
			<xs:element name="value" type="xs:string" minOccurs="1"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="values" />
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="constraint">
		<xs:sequence>
			<xs:element name="targetResourceIDRef" type="xs:string" />
			<xs:element name="targetClass" type="xs:string" minOccurs="0"/>
			<xs:element name="metric" type="xs:string" />
			<xs:element name="metricAggregation" type="cons:qosMetricAggregation"
				minOccurs="0" />
			<xs:element name="range" type="cons:range" />
			<xs:element name="priority" type="xs:nonNegativeInteger"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" />
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="qosMetricAggregation">
		<xs:sequence>
			<xs:element name="parameter" type="pa:parameter" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="parameters" />
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="aggregateFunction" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="range">
		<xs:sequence>
			<xs:element name="hasMaxValue" type="xs:float" minOccurs="0" />
			<xs:element name="hasMinValue" type="xs:float" minOccurs="0" />
			<xs:element name="inSet" type="cons:set" minOccurs="0" />
			<xs:element name="outSet" type="cons:set" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/mic/constraint.xml
<?xml version="1.0"?>
<constraints xmlns="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/qosconstraints/qos_constraints_schema.xsd">
	<constraint
		id="c1"
		name="loginAverage">
		<targetResourceIDRef>_FIHtgIGMEeK4MfbIE3-zwQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>1000</hasMaxValue>
		</range>
	</constraint>
	<constraint
		id="c2"
		name="loginPercentile">
		<targetResourceIDRef>_FIHtgIGMEeK4MfbIE3-zwQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Percentile">
			<parameter name="thPercentile">85</parameter>
		</metricAggregation>
		<range>
			<hasMaxValue>800</hasMaxValue>
		</range>
	</constraint>
	<constraint
		id="c3"
		name="updateDataAverage">
		<targetResourceIDRef>_FHrooIGMEeK4MfbIE3-zwQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>2000</hasMaxValue>
		</range>
	</constraint>
	<constraint
		id="c4"
		name="updateDataPercentile">
		<targetResourceIDRef>Id	_FHrooIGMEeK4MfbIE3-zwQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Percentile">
			<parameter name="thPercentile">85</parameter>
		</metricAggregation>
		<range>
			<hasMaxValue>1500</hasMaxValue>
		</range>
	</constraint>
	<constraint
		id="c5"
		name="frontEndAverageRT">
		<targetResourceIDRef>_T1b94IGJEeK4MfbIE3-zwQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>5000</hasMaxValue>
		</range>
	</constraint>
	<constraint
		id="a1"
		name="webServerUtilization">
		<targetResourceIDRef>_WHZKsIGPEeKo6LTSAnjWxg</targetResourceIDRef>
		<targetClass>VM</targetClass>
		<metric>CPUUtilization</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>0.8</hasMaxValue>
		</range>
	</constraint>
		<constraint
		id="a2"
		name="webServerMinRAM">
		<targetResourceIDRef>_WHZKsIGPEeKo6LTSAnjWxg</targetResourceIDRef>
		<targetClass>VM</targetClass>
		<metric>RAM</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMinValue>4096</hasMinValue>
		</range>
	</constraint>
	<constraint id="a3" name="Mail does not Scale">
		<targetResourceIDRef>_MNm6wIGSEeKo6LTSAnjWxg</targetResourceIDRef>
		<targetClass>VM</targetClass>
		<metric>Replication</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>1</hasMaxValue>
			<hasMinValue>1</hasMinValue>
		</range>
	</constraint>
</constraints>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/ehealth/QoSConstraints.xml
<?xml version="1.0"?>
<constraints xmlns="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/qosconstraints/qos_constraints_schema.xsd">
    <constraint
        id="7c71d46a-578d-495c-9f19-65b0e5b16520_87c5a68c-c136-41ae-9d52-b8b2d3737873_a6cfcd1b-78b2-4b98-83f1-ae0b41608078_seff"
        name="ResponseTime_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_a6cfcd1b-78b2-4b98-83f1-ae0b41608078_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>ResponseTime</metric>
        <metricAggregation aggregateFunction="Average" />
        <range>
            <hasMaxValue>10000</hasMaxValue>
        </range>
        <priority>2</priority>
    </constraint>
    <constraint
        id="7c71d46a-578d-495c-9f19-65b0e5b16520_87c5a68c-c136-41ae-9d52-b8b2d3737873_06fb870e-b5d6-47b1-8517-ef0665c24746_seff"
        name="ResponseTime_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_06fb870e-b5d6-47b1-8517-ef0665c24746_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>ResponseTime</metric>
        <metricAggregation aggregateFunction="Average" />
        <range>
            <hasMaxValue>10000</hasMaxValue>
        </range>
        <priority>2</priority>
    </constraint>
    <constraint
        id="7c71d46a-578d-495c-9f19-65b0e5b16520_87c5a68c-c136-41ae-9d52-b8b2d3737873_67c2d700-7af0-4cb2-938a-63d58b602970_seff"
        name="ResponseTime_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_67c2d700-7af0-4cb2-938a-63d58b602970_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>ResponseTime</metric>
        <metricAggregation aggregateFunction="Average" />
        <range>
            <hasMaxValue>10000</hasMaxValue>
        </range>
        <priority>2</priority>
    </constraint>
    <constraint
        id="522b6258-9958-4116-ab3e-9711f72ac027_87c5a68c-c136-41ae-9d52-b8b2d3737873_a6cfcd1b-78b2-4b98-83f1-ae0b41608078_seff"
        name="Avialability_wa">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_a6cfcd1b-78b2-4b98-83f1-ae0b41608078_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="522b6258-9958-4116-ab3e-9711f72ac027_87c5a68c-c136-41ae-9d52-b8b2d3737873_642bae79-ccdc-46f1-9da5-493bb75a88c1_seff"
        name="Avialability_wa">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_642bae79-ccdc-46f1-9da5-493bb75a88c1_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="522b6258-9958-4116-ab3e-9711f72ac027_87c5a68c-c136-41ae-9d52-b8b2d3737873_06fb870e-b5d6-47b1-8517-ef0665c24746_seff"
        name="Avialability_wa">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_06fb870e-b5d6-47b1-8517-ef0665c24746_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="522b6258-9958-4116-ab3e-9711f72ac027_87c5a68c-c136-41ae-9d52-b8b2d3737873_67c2d700-7af0-4cb2-938a-63d58b602970_seff"
        name="Avialability_wa">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_67c2d700-7af0-4cb2-938a-63d58b602970_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="47c18e9b-5f8f-47d2-996c-f0a6372294f8_87c5a68c-c136-41ae-9d52-b8b2d3737873_a6cfcd1b-78b2-4b98-83f1-ae0b41608078_seff"
        name="Avialability_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_a6cfcd1b-78b2-4b98-83f1-ae0b41608078_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="47c18e9b-5f8f-47d2-996c-f0a6372294f8_87c5a68c-c136-41ae-9d52-b8b2d3737873_642bae79-ccdc-46f1-9da5-493bb75a88c1_seff"
        name="Avialability_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_642bae79-ccdc-46f1-9da5-493bb75a88c1_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="47c18e9b-5f8f-47d2-996c-f0a6372294f8_87c5a68c-c136-41ae-9d52-b8b2d3737873_06fb870e-b5d6-47b1-8517-ef0665c24746_seff"
        name="Avialability_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_06fb870e-b5d6-47b1-8517-ef0665c24746_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
    <constraint
        id="47c18e9b-5f8f-47d2-996c-f0a6372294f8_87c5a68c-c136-41ae-9d52-b8b2d3737873_67c2d700-7af0-4cb2-938a-63d58b602970_seff"
        name="Avialability_ws">
        <targetResourceIDRef>87c5a68c-c136-41ae-9d52-b8b2d3737873_67c2d700-7af0-4cb2-938a-63d58b602970_seff</targetResourceIDRef>
        <targetClass>Method</targetClass>
        <metric>Availability</metric>
        <metricAggregation aggregateFunction="99thPercentile" />
        <range />
        <priority>1</priority>
    </constraint>
</constraints>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/SimpleModel/QoSConstraints.xml
<?xml version="1.0"?>
<constraints xmlns="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/qosconstraints/qos_constraints_schema.xsd">
  <constraint id="b2dc3727-df68-4b2a-b0d4-886b5aa75496_39b66f7c-f48e-4ed1-bce1-511a1cf8606d__resourceContainer" name="QoS Constraint">
    <targetResourceIDRef>39b66f7c-f48e-4ed1-bce1-511a1cf8606d__resourceContainer</targetResourceIDRef>
    <targetClass>VM</targetClass>
    <metric>CPUUtilization</metric>
    <metricAggregation aggregateFunction="Average"/>
    <range/>
  </constraint>
  <constraint id="b2dc3727-df68-4b2a-b0d4-886b5aa75496_CloudNodeInstance_SampleCloudNode" name="QoS Constraint">
    <targetResourceIDRef>CloudNodeInstance_SampleCloudNode</targetResourceIDRef>
    <targetClass>VM</targetClass>
    <metric>Memory</metric>
    <metricAggregation aggregateFunction="Average"/>
    <range/>
  </constraint>
  <constraint id="b2dc3727-df68-4b2a-b0d4-886b5aa75496_ServiceApplicationType" name="QoS Constraint">
    <targetResourceIDRef>ServiceApplicationType</targetResourceIDRef>
    <targetClass>InternalComponent</targetClass>
    <metric>Memory</metric>
    <metricAggregation aggregateFunction="Average"/>
    <range/>
  </constraint>
  <constraint id="b2dc3727-df68-4b2a-b0d4-886b5aa75496_20502386-8336-4ee8-b686-6abe774d1a43" name="QoS Constraint">
    <targetResourceIDRef>20502386-8336-4ee8-b686-6abe774d1a43</targetResourceIDRef>
    <targetClass>InternalComponent</targetClass>
    <metric>Memory</metric>
    <metricAggregation aggregateFunction="Average"/>
    <range/>
  </constraint>
  <constraint id="b2dc3727-df68-4b2a-b0d4-886b5aa75496_ec84b104-aff1-4509-adc5-630e4396e4c1" name="QoS Constraint">
    <targetResourceIDRef>ec84b104-aff1-4509-adc5-630e4396e4c1</targetResourceIDRef>
    <targetClass>InternalComponent</targetClass>
    <metric>Memory</metric>
    <metricAggregation aggregateFunction="Average"/>
    <range/>
  </constraint>
</constraints>

=== modaclouds/modaclouds-sla-mediator/src/main/resources/xsd/metamodels/examples/qos_constraints_SpecWeb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<constraints xmlns="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema ../qosconstraints/qos_constraints_schema.xsd">
	<!--the average response time for component with id:_GdmYEMhsEeKON4DtRoKCMw 
		should be lower than 2000ms -->
	<constraint id="c1" name="ResponseTime">
		<targetResourceIDRef>_GdmYEMhsEeKON4DtRoKCMw</targetResourceIDRef>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>2000</hasMaxValue>
		</range>
	</constraint>
	<!--the 95th percentile of response time for component with id:_GdmYEMhsEeKON4DtRoKCMw 
		should be lower than 3000ms -->
	<constraint id="c2" name="ResponseTime">
		<targetResourceIDRef>_GdmYEMhsEeKON4DtRoKCMw</targetResourceIDRef>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Percentile">
			<parameter name="thPercentile">95</parameter>
		</metricAggregation>
		<range>
			<hasMaxValue>3000</hasMaxValue>
		</range>
	</constraint>
	<!-- meaning: the application should not run on Azure -->
	<constraint id="c3" name="notAzure">
		<targetResourceIDRef>m1</targetResourceIDRef>
		<metric>Provider</metric>
		<range>
			<outSet>
				<value>Azure</value>
			</outSet>
		</range>
	</constraint>
	<!-- meaning: the application should run only on Amazon or Flexi (or both) -->
	<constraint id="c4" name="choice of providers">
		<targetResourceIDRef>m1</targetResourceIDRef>
		<metric>Provider</metric>
		<range>
			<inSet>
				<value>Amazon</value>
				<value>Flexiscale</value>
			</inSet>
		</range>
	</constraint>
	<!-- meaning: each chosen provider should process at least 20% of the incoming 
		traffic. -->
	<constraint id="c6" name="minimum Workload partitioning">
		<targetResourceIDRef>m1</targetResourceIDRef>
		<metric>WorkloadDistribution</metric>
		<range>
			<hasMinValue>20</hasMinValue>
		</range>
		<priority>2</priority>
	</constraint>
	<!-- meaning: the application should run at least on 2 providers -->
	<constraint id="c7" name="minimum providers">
		<targetResourceIDRef>m1</targetResourceIDRef>
		<metric>Provider</metric>
		<range>
			<hasMinValue>2</hasMinValue>
		</range>
	</constraint>
	<!-- meaning: the application should run at most on 3 providers -->
	<constraint id="c8" name="minimum providers">
		<targetResourceIDRef>m1</targetResourceIDRef>
		<metric>Provider</metric>
		<range>
			<hasMaxValue>3</hasMaxValue>
		</range>
	</constraint>
	<!-- meaning: at least 30% of the workload has to be processed by Amazon -->
	<constraint id="c9" name="Minimum workload on Amazon">
		<targetResourceIDRef>Amazon</targetResourceIDRef>
		<metric>WorkloadDistribution</metric>
		<range>
			<hasMinValue>30</hasMinValue>
		</range>
	</constraint>
</constraints>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/mic2/QoSConstraints.xml
<?xml version="1.0"?>
<constraints xmlns="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/qosconstraints/qos_constraints_schema.xsd">
	<constraint
		id="r1"
		name="register">
		<targetResourceIDRef>_sPjOMNhwEeSGjb1hTo3-zQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>4000</hasMaxValue>
		</range>
	</constraint>

	<constraint
		id="r2" name="Login percentile RT">
		<targetResourceIDRef>_sPjOMNhwEeSGjb1hTo3-zQ</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Percentile">
			<parameter name="thPercentile">95</parameter>
		</metricAggregation>
		<range>
			<hasMaxValue>10000</hasMaxValue>
		</range>
	</constraint>

	<constraint
		id="r3" name="Answere Question Average">
		<targetResourceIDRef>_GUDXEMdIEeSzTs-iRu8Llw</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>10000</hasMaxValue>
		</range>
	</constraint>


	<constraint id="3" name="Front End Minimum Ram">
		<targetResourceIDRef>_JWHSgMdLEeSzTs-iRu8Llw</targetResourceIDRef>
		<metric>RAM</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMinValue>2000</hasMinValue>
		</range>
	</constraint>
	<constraint id="4" name="Min Ram">
		<targetResourceIDRef>_JWHSgMdLEeSzTs-iRu8Llw</targetResourceIDRef>
		<metric>RAM</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMinValue>2000</hasMinValue>
		</range>
	</constraint>
	<constraint id="5" name="Max Utilization">
		<targetResourceIDRef>_JWHSgMdLEeSzTs-iRu8Llw</targetResourceIDRef>
		<metric>CPUUtilization</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>0.8</hasMaxValue>
		</range>
	</constraint>
	<constraint
		id="6"
		name="MachineType">
		<targetResourceIDRef>_JWHSgMdLEeSzTs-iRu8Llw</targetResourceIDRef>
		<targetClass>VM</targetClass>
		<metric>MachineType</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<outSet>
				<value>c3.large</value>
			</outSet>
		</range>
	</constraint>
</constraints>

=== modaclouds/modaclouds-sla-mediator/src/test/resources/ofbiz/QoSConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014 deib-polimi
    Contact: deib-polimi <marco.miglierina@polimi.it>

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<constraints xmlns="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema https://raw.githubusercontent.com/deib-polimi/modaclouds-qos-models/master/metamodels/qosconstraints/qos_constraints_schema.xsd"	>
	<!--the average response time for the quickadd functionality lower than 2 seconds -->
	<constraint id="c1" name="quickaddRT">
		<targetResourceIDRef>_EkA9EMhoEeKON4DtRoKCMw</targetResourceIDRef>
		<targetClass>Method</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>2</hasMaxValue>
		</range>
	</constraint>
	<!--the average response time for all the functionalities of the request handler component lower than 5 seconds -->
	<constraint id="c2" name="requestHandlerRT">
		<targetResourceIDRef>__o5G4MhnEeKON4DtRoKCMw</targetResourceIDRef>
		<targetClass>InternalComponent</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>5</hasMaxValue>
		</range>
	</constraint>
		<!--the average response time of the query functionality lower than 1 second -->
	<constraint id="c3" name="requestHandlerRT">
		<targetResourceIDRef>_lpzSMMhoEeKON4DtRoKCMw</targetResourceIDRef>
		<targetClass>InternalComponent</targetClass>
		<metric>ResponseTime</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>1</hasMaxValue>
		</range>
	</constraint>
	
<!--the average cpu load of the backend lower than 80% -->
	<constraint id="c4" name="requestHandlerRT">
		<targetResourceIDRef>_ervoQKhyEeOVLLp4qCj_jg</targetResourceIDRef>
		<targetClass>VM</targetClass>
		<metric>CPUUtilization</metric>
		<metricAggregation aggregateFunction="Average" />
		<range>
			<hasMaxValue>0.8</hasMaxValue>
		</range>
	</constraint>
</constraints>
